### ISSUE TITLE
Do fizzbuzz with if, for statements

### ISSUE THREAD

**Issue by jinsoooo49** [jinsoooo49/team-fizzbuzz#1]
## Tasks

- [ ] While i goes up 1 to 16
- [ ] Print 'fizz' if i is times of 3
- [ ] Print 'buzz' if i is times of 5
- [ ] Print 'fizzbuzz' if i times of 15
- [ ] else, print i itself.
